
'use client';

import { useState } from 'react';
import { Scan, Image as ImageIcon, ShieldAlert, ShieldCheck, Loader2, Info } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../ui/card';
import { Button } from '../ui/button';
import { Progress } from '../ui/progress';
import { Badge } from '../ui/badge';
import { detectAiImage } from '@/lib/image-actions';
import type { ImageAnalysisResult } from '@/lib/types';
import { useToast } from '@/hooks/use-toast';
import Image from 'next/image';

export function ImageDetectorPage() {
  const [analyzing, setAnalyzing] = useState(false);
  const [result, setResult] = useState<ImageAnalysisResult | null>(null);
  const { toast } = useToast();

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.type.startsWith('image/')) {
        toast({ variant: 'destructive', title: 'Invalid File', description: 'Please select an image file.' });
        return;
    }

    setAnalyzing(true);
    setResult(null);

    try {
        const reader = new FileReader();
        reader.onloadend = async () => {
            const dataUri = reader.result as string;
            const analysis = await detectAiImage(dataUri);
            setResult(analysis);
            setAnalyzing(false);
        };
        reader.readAsDataURL(file);
    } catch (error) {
        console.error(error);
        toast({ variant: 'destructive', title: 'Analysis Failed', description: 'Could not process the image.' });
        setAnalyzing(false);
    }
  };

  return (
    <Card className="w-full max-w-3xl bg-card/30 backdrop-blur-lg border-primary/20 animate-in fade-in zoom-in-95">
        <CardHeader>
            <CardTitle className="flex items-center gap-2 text-2xl text-primary-foreground">
                <Scan className="text-primary w-8 h-8" />
                AI Image Detector
            </CardTitle>
            <CardDescription>Upload an image to detect if it was generated by an AI or captured by a real camera.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
            <div className="flex flex-col items-center justify-center border-2 border-dashed border-border/50 rounded-xl p-8 bg-background/20">
                {result?.imageUrl ? (
                    <div className="relative w-full max-w-md aspect-video mb-4 rounded-lg overflow-hidden border border-primary/20">
                        <Image src={result.imageUrl} alt="Uploaded for analysis" fill className="object-contain" />
                    </div>
                ) : (
                    <ImageIcon className="w-16 h-16 text-muted-foreground mb-4" />
                )}
                <input
                    type="file"
                    id="image-upload"
                    accept="image/*"
                    className="hidden"
                    onChange={handleFileChange}
                    disabled={analyzing}
                />
                <Button asChild disabled={analyzing} className="cursor-target">
                    <label htmlFor="image-upload">
                        {analyzing ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <ImageIcon className="mr-2 h-4 w-4" />}
                        {analyzing ? 'Analyzing Image...' : 'Select Image'}
                    </label>
                </Button>
            </div>

            {result && (
                <div className="space-y-6 animate-in slide-in-from-bottom-4 duration-500">
                    <div className="flex items-center justify-between p-4 rounded-lg bg-background/50 border border-primary/20">
                        <div className="flex items-center gap-3">
                            {result.isAiGenerated ? <ShieldAlert className="text-destructive w-10 h-10" /> : <ShieldCheck className="text-accent w-10 h-10" />}
                            <div>
                                <h3 className={`text-xl font-bold ${result.isAiGenerated ? 'text-destructive' : 'text-accent'}`}>
                                    {result.isAiGenerated ? 'AI Detected' : 'Likely Authentic'}
                                </h3>
                                <p className="text-sm text-muted-foreground">Confidence Level: {result.isAiGenerated ? result.finalScore.toFixed(1) : (100 - result.finalScore).toFixed(1)}%</p>
                            </div>
                        </div>
                        <Badge variant={result.isAiGenerated ? 'destructive' : 'default'} className={!result.isAiGenerated ? 'bg-accent' : ''}>
                             Score: {result.finalScore.toFixed(0)}/100
                        </Badge>
                    </div>

                    <div className="space-y-2">
                        <div className="flex justify-between text-sm">
                            <span className="text-muted-foreground">AI Probability</span>
                            <span className="font-bold">{result.finalScore.toFixed(1)}%</span>
                        </div>
                        <Progress value={result.finalScore} className="h-2" />
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <Card className="bg-background/40 border-primary/10">
                            <CardHeader className="p-4">
                                <CardTitle className="text-sm flex items-center gap-2">
                                    <Info className="w-4 h-4 text-primary" />
                                    Metadata Analysis (40%)
                                </CardTitle>
                            </CardHeader>
                            <CardContent className="p-4 pt-0 text-xs">
                                <p className="mb-2 text-muted-foreground">Checks for EXIF signatures, camera models, and AI software tags.</p>
                                <ul className="list-disc pl-4 space-y-1">
                                    {result.metadataFindings.map((f, i) => (
                                        <li key={i}>{f}</li>
                                    ))}
                                </ul>
                            </CardContent>
                        </Card>
                        <Card className="bg-background/40 border-primary/10">
                            <CardHeader className="p-4">
                                <CardTitle className="text-sm flex items-center gap-2">
                                    <Scan className="w-4 h-4 text-primary" />
                                    AI Vision Scan (60%)
                                </CardTitle>
                            </CardHeader>
                            <CardContent className="p-4 pt-0 text-xs">
                                <p className="mb-2 text-muted-foreground">Visual artifact inspection by our neural engine.</p>
                                <p className="italic text-muted-foreground">"{result.aiExplanation}"</p>
                            </CardContent>
                        </Card>
                    </div>
                </div>
            )}
        </CardContent>
    </Card>
  );
}
